baseurl = "https://samadipour.github.io"
title = "SamadiPour"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10
canonifyurls = true

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[markup.goldmark.renderer]
unsafe= true


[params]
    author = "A.H. SamadiPour"
    description = "A.H. SamadiPour Personal Website"
    keywords = "blog,developer,personal,SamadiPour"
    info = "Mobile Application Developer"
    avatarurl = "images/profile.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideFooter = true
    hideCredits = true
    hideCopyright = true
    since = 2012

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    enableTwemoji = true
    custom_css = []
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/samadipour/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/samadipour/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in"
    weight = 2
    url = "https://www.linkedin.com/in/samadipour/"    
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram-plane"
    weight = 4
    url = "https://t.me/iAmSamadiPour/"

#[[params.social]]
#    name = "Virgool"
#    icon = "fab fa-medium"
#    weight = 5
#    url = "https://medium.com/@johndoe"

[languages]
    [languages.en]
        languagename = "English"
        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 2
            url = "projects/"